<?php

declare(strict_types=1);

$sources = [
    'unicef-baby' => ['UNICEF - 21 learning activities for babies and toddlers', 'https://www.unicef.org/parenting/child-care/21-learning-activities-babies-and-toddlers'],
    'unicef-play' => ['UNICEF - 5 fun ideas for learning through play', 'https://www.unicef.org/parenting/child-care/5-fun-ideas-for-learning-through-play'],
    'harvard' => ['Harvard Center - Activities Guide', 'https://developingchild.harvard.edu/resources/handouts-tools/activities-guide-enhancing-and-practicing-executive-function-skills/'],
    'harvard-7-12' => ['Harvard Center - Executive Function Activities for 7-12', 'https://developingchild.harvard.edu/wp-content/uploads/2024/10/Executive-Function-Activities-for-7-to-12-year-olds.pdf'],
];

$situations = [
    ['connection', 'bored', 'indoor-time'], ['restless', 'calm-down', 'indoor-time'],
    ['connection', 'restless', 'bored'], ['calm-down', 'bored', 'indoor-time'],
    ['connection', 'restless', 'calm-down'],
];

$make = static function (
    string $slug, string $title, string $summary, array $instructions, string $safety, string $band,
    int $minAge, int $maxAge, int $slot, string $source, array $overrides = []
) use ($sources, $situations): array {
    [$sourceTitle, $sourceUrl] = $sources[$source];
    $metadata = array_replace([
        'age_band' => $band, 'minimum_age_months' => $minAge, 'maximum_age_months_exclusive' => $maxAge,
        'duration_min_minutes' => 5, 'duration_max_minutes' => 12, 'prep_time_minutes' => 0,
        'space_required' => 'small', 'noise_level' => 'quiet', 'mess_level' => 'none',
        'minimum_children' => 1, 'maximum_children' => 2, 'minimum_adults' => 1, 'required_adult' => true,
        'child_energy' => 'low', 'caregiver_energy' => 'low', 'interaction_type' => 'cooperative',
        'caregiver_involvement' => 'shared', 'setup_complexity' => 'none',
        'source_title' => $sourceTitle, 'source_url' => $sourceUrl,
        'cultural_origin' => 'بازی عمومی خانوادگی؛ بازنویسی فارسی',
        'situations' => $situations[$slot], 'locations' => ['home-inside'], 'moods' => ['calm', 'restless'],
        'tags' => ['cooperative'], 'player_requirement' => 'child-and-adult', 'materials' => [],
        'safety_flags' => ['sensory_intensity'],
    ], $overrides);

    return [
        'slug' => $slug, 'title' => $title, 'summary' => $summary, 'instructions' => $instructions,
        'safety_copy' => $safety, 'contraindications' => [], 'supervision_level' => $minAge < 48 ? 'within_reach' : 'same_room',
        'metadata' => $metadata,
    ];
};

return [
    $make('face-mirror', 'آینه‌ی شکلک‌ها', 'همراه حالت‌های ساده صورت را نشان می‌دهد و به پاسخ کودک فرصت می‌دهد', ['روبه‌روی کودک بنشینید', 'یک حالت ساده مثل لبخند نشان دهید', 'مکث کنید و پاسخ کودک را تقلید کنید'], 'اگر کودک روی برمی‌گرداند یا بی‌قرار می‌شود، بازی را متوقف کنید', '6-23m', 6, 24, 0, 'unicef-baby', ['space_required' => 'lap', 'duration_min_minutes' => 3, 'duration_max_minutes' => 8, 'interaction_type' => 'conversation', 'caregiver_involvement' => 'active', 'tags' => ['language', 'cooperative']]),
    $make('song-and-pause', 'آواز و مکث', 'یک آواز کوتاه با مکث‌های منتظرانه به بازی نوبتی تبدیل می‌شود', ['یک آواز آشنا را آرام بخوانید', 'در پایان هر بخش مکث کنید', 'به صدا یا حرکت کودک پاسخ دهید'], 'صدا را آرام نگه دارید و با نخستین نشانه ناراحتی مکث کنید', '6-23m', 6, 24, 1, 'unicef-baby', ['space_required' => 'lap', 'duration_min_minutes' => 3, 'duration_max_minutes' => 7, 'noise_level' => 'moderate', 'interaction_type' => 'conversation', 'caregiver_involvement' => 'active', 'tags' => ['language', 'cooperative']]),
    $make('follow-my-hands', 'دنبال دست‌های من', 'حرکت آهسته دست همراه، نگاه و رسیدن کودک را به رفت‌وبرگشت کوتاه تبدیل می‌کند', ['کودک را در وضعیت پایدار قرار دهید', 'دست را آرام از یک سمت به سمت دیگر ببرید', 'پس از دنبال‌کردن مکث کنید'], 'کودک را برای رسیدن یا چرخیدن مجبور نکنید', '6-23m', 6, 24, 2, 'unicef-baby', ['duration_min_minutes' => 3, 'duration_max_minutes' => 6, 'child_energy' => 'medium', 'interaction_type' => 'side_by_side', 'caregiver_involvement' => 'active', 'tags' => ['movement', 'cooperative'], 'safety_flags' => ['fall_height']]),
    $make('where-is-the-sound', 'صدا از کجاست', 'صدای آرام همراه از جهت‌های نزدیک، کودک را به پیدا کردن منبع صدا دعوت می‌کند', ['کنار کودک و در میدان دید او بنشینید', 'نام کودک را آرام از یک سمت بگویید', 'پس از پیدا کردن صدا جهت را عوض کنید'], 'صدا را ناگهانی یا نزدیک گوش کودک تولید نکنید', '6-23m', 6, 24, 3, 'unicef-baby', ['space_required' => 'lap', 'duration_min_minutes' => 3, 'duration_max_minutes' => 6, 'interaction_type' => 'conversation', 'tags' => ['sensory', 'language']]),
    $make('copy-baby', 'تو بگو، من تکرار می‌کنم', 'همراه صداها و حرکت‌های کودک را تقلید می‌کند تا کودک رهبر بازی باشد', ['به حرکت یا صدای کودک توجه کنید', 'همان را آرام تقلید کنید', 'مکث کنید تا کودک نوبت بعد را آغاز کند'], 'بازی را کوتاه نگه دارید و نشانه‌های خستگی را جدی بگیرید', '6-23m', 6, 24, 4, 'unicef-baby', ['space_required' => 'lap', 'duration_min_minutes' => 3, 'duration_max_minutes' => 8, 'interaction_type' => 'conversation', 'caregiver_involvement' => 'active', 'tags' => ['language', 'cooperative']]),

    $make('cup-tower', 'برج لیوانی', 'کودک و همراه لیوان‌ها را روی هم می‌چینند و دوباره از نو می‌سازند', ['لیوان‌های سبک را روی زمین بگذارید', 'نوبتی یک لیوان اضافه کنید', 'برج را خراب و دوباره بسازید'], 'فقط از لیوان سبک و نشکن استفاده کنید', '2-3y', 24, 48, 0, 'unicef-baby', ['prep_time_minutes' => 2, 'child_energy' => 'medium', 'tags' => ['creative', 'cooperative'], 'materials' => [['slug' => 'cups', 'requirement' => 'required', 'quantity_note' => '۳ تا ۶ لیوان سبک و نشکن']], 'safety_flags' => ['small_parts']]),
    $make('animal-walk', 'راه‌رفتن حیوان‌ها', 'کودک و همراه حرکت چند حیوان را آرام و خنده‌دار تقلید می‌کنند', ['یک حیوان با حرکت ساده انتخاب کنید', 'حرکت را آهسته نشان دهید', 'نقش انتخاب حیوان را عوض کنید'], 'فضا را از لبه و مانع خالی کنید و حرکت‌های پرشی را حذف کنید', '2-3y', 24, 48, 1, 'harvard', ['space_required' => 'room', 'noise_level' => 'moderate', 'child_energy' => 'high', 'caregiver_energy' => 'medium', 'interaction_type' => 'pretend', 'caregiver_involvement' => 'active', 'locations' => ['home-inside', 'home-outside'], 'moods' => ['restless', 'excited'], 'tags' => ['movement', 'creative'], 'safety_flags' => ['fall_height', 'high_impact']]),
    $make('color-hunt-toddler', 'رنگ را پیدا کن', 'همراه یک رنگ می‌گوید و کودک در فضای نزدیک چیزی هم‌رنگ پیدا می‌کند', ['یک رنگ آشنا را نام ببرید', 'از کودک بخواهید همان رنگ را نشان دهد', 'پس از پاسخ رنگ بعدی را بگویید'], 'فقط اشیای در دسترس را انتخاب کنید و اجازه بالارفتن ندهید', '2-3y', 24, 48, 2, 'unicef-baby', ['space_required' => 'room', 'child_energy' => 'medium', 'tags' => ['language', 'movement'], 'safety_flags' => ['fall_height']]),
    $make('half-story-toddler', 'قصه‌ی نیمه‌کاره', 'همراه یک قصه کوتاه می‌گوید و کودک با صدا یا حرکت ادامه‌اش می‌دهد', ['قصه را با یک شخصیت آشنا شروع کنید', 'پس از یک جمله مکث کنید', 'پاسخ کودک را در جمله بعد وارد کنید'], 'از صدای ناگهانی و موضوع ترسناک استفاده نکنید', '2-3y', 24, 48, 3, 'harvard', ['space_required' => 'lap', 'interaction_type' => 'conversation', 'caregiver_involvement' => 'active', 'locations' => ['home-inside', 'travel'], 'moods' => ['calm', 'sad'], 'tags' => ['language', 'creative']]),
    $make('laundry-sort', 'جورچین لباس‌ها', 'لباس‌های تمیز با رنگ یا اندازه به دسته‌های ساده تقسیم می‌شوند', ['چند لباس تمیز را روی زمین بگذارید', 'یک قانون ساده انتخاب کنید', 'با هم دسته‌بندی و جمع کنید'], 'کیسه پلاستیکی، بند بلند و قطعه جداشدنی را وارد بازی نکنید', '2-3y', 24, 48, 4, 'unicef-baby', ['duration_min_minutes' => 6, 'prep_time_minutes' => 2, 'mess_level' => 'light', 'interaction_type' => 'side_by_side', 'materials' => [['slug' => 'blanket', 'requirement' => 'optional', 'quantity_note' => 'سطح تمیز برای چیدن لباس‌ها']], 'tags' => ['cooperative', 'sensory'], 'safety_flags' => ['strangulation']]),

    $make('clap-statue', 'مجسمه با دست‌زدن', 'کودک با ریتم دست‌زدن حرکت می‌کند و با قطع صدا بی‌حرکت می‌ماند', ['فضای حرکت را خالی کنید', 'با دست‌زدن آرام ریتم بسازید', 'مکث کنید و مثل مجسمه بایستید'], 'دویدن و پریدن کنار وسایل را حذف کنید', '4-6y', 48, 84, 0, 'unicef-play', ['duration_min_minutes' => 6, 'duration_max_minutes' => 15, 'space_required' => 'room', 'noise_level' => 'moderate', 'child_energy' => 'high', 'caregiver_energy' => 'medium', 'caregiver_involvement' => 'active', 'locations' => ['home-inside', 'home-outside'], 'moods' => ['restless', 'excited'], 'tags' => ['movement', 'cooperative'], 'safety_flags' => ['fall_height', 'high_impact']]),
    $make('blanket-path', 'مسیر پتویی', 'یک پتوی پهن‌شده به مسیر خیالی برای قدم‌های آهسته تبدیل می‌شود', ['پتو را صاف روی سطح بدون لغزش پهن کنید', 'مسیر را جاده خیالی بنامید', 'نوبتی روی مسیر قدم بزنید'], 'لبه پتو نباید جمع یا لغزنده باشد و دویدن ممنوع است', '4-6y', 48, 84, 1, 'harvard', ['duration_min_minutes' => 8, 'duration_max_minutes' => 15, 'prep_time_minutes' => 2, 'space_required' => 'room', 'mess_level' => 'light', 'child_energy' => 'medium', 'caregiver_energy' => 'medium', 'interaction_type' => 'pretend', 'materials' => [['slug' => 'blanket', 'requirement' => 'required', 'quantity_note' => 'یک پتوی کوچک و بدون لغزش']], 'tags' => ['movement', 'creative'], 'safety_flags' => ['fall_height']]),
    $make('picture-chain', 'زنجیره‌ی نقاشی', 'هر نفر یک خط به نقاشی اضافه می‌کند تا تصویر مشترک شکل بگیرد', ['یک کاغذ آماده کنید', 'نفر اول یک شکل ساده بکشد', 'نوبتی یک بخش اضافه کنید'], 'از ابزار نقاشی مناسب سن و غیرسمی استفاده کنید', '4-6y', 48, 84, 2, 'harvard', ['duration_min_minutes' => 8, 'duration_max_minutes' => 18, 'prep_time_minutes' => 2, 'mess_level' => 'light', 'interaction_type' => 'cooperative', 'materials' => [['slug' => 'paper', 'requirement' => 'required', 'quantity_note' => 'یک یا دو برگ کاغذ']], 'moods' => ['calm', 'sad'], 'tags' => ['creative', 'cooperative'], 'safety_flags' => ['ingestion']]),
    $make('story-sound-effects', 'صدای قصه', 'یک قصه کوتاه با صداهای انتخابی کودک جان می‌گیرد', ['یک قصه ساده شروع کنید', 'برای دو اتفاق صدای کوتاه انتخاب کنید', 'در قصه مکث کنید تا کودک صدا را بسازد'], 'صداها را ملایم نگه دارید و با ناراحتی کودک موضوع را عوض کنید', '4-6y', 48, 84, 3, 'harvard', ['duration_min_minutes' => 6, 'duration_max_minutes' => 15, 'space_required' => 'lap', 'noise_level' => 'moderate', 'interaction_type' => 'conversation', 'caregiver_involvement' => 'active', 'locations' => ['home-inside', 'travel'], 'moods' => ['calm', 'sad'], 'tags' => ['language', 'creative']]),
    $make('soft-ball-gate', 'دروازه‌ی توپ نرم', 'توپ نرم نوبتی از میان یک دروازه خیالی به سمت هم قل داده می‌شود', ['دو نشانه امن برای دروازه بگذارید', 'روبه‌روی هم روی زمین بنشینید', 'توپ را نوبتی از دروازه قل دهید'], 'فقط توپ نرم استفاده شود و توپ پرتاب نشود', '4-6y', 48, 84, 4, 'unicef-play', ['duration_min_minutes' => 6, 'duration_max_minutes' => 15, 'prep_time_minutes' => 2, 'space_required' => 'room', 'noise_level' => 'moderate', 'child_energy' => 'medium', 'caregiver_energy' => 'medium', 'locations' => ['home-inside', 'home-outside'], 'moods' => ['restless', 'excited'], 'tags' => ['movement', 'cooperative'], 'materials' => [['slug' => 'ball', 'requirement' => 'required', 'quantity_note' => 'یک توپ نرم و سبک']], 'safety_flags' => ['high_impact']]),

    $make('paper-treasure-map', 'نقشه‌ی گنج کاغذی', 'کودک و همراه نقشه‌ای ساده می‌کشند و یک مقصد خیالی پیدا می‌کنند', ['سه نقطه آشنا را روی کاغذ علامت بزنید', 'یک مسیر ساده بکشید', 'با هم مسیر را طی کنید'], 'مسیر نباید از پله، بالارفتن یا محل خطرناک عبور کند', '7-9y', 84, 120, 0, 'harvard', ['duration_min_minutes' => 12, 'duration_max_minutes' => 25, 'prep_time_minutes' => 3, 'space_required' => 'room', 'mess_level' => 'light', 'child_energy' => 'medium', 'caregiver_energy' => 'medium', 'materials' => [['slug' => 'paper', 'requirement' => 'required', 'quantity_note' => 'یک برگ کاغذ']], 'tags' => ['creative', 'cooperative'], 'safety_flags' => ['fall_height']]),
    $make('silent-charades', 'پانتومیم بی‌صدا', 'هر نفر یک کار روزمره را بی‌صدا اجرا می‌کند و دیگری حدس می‌زند', ['یک کار ساده انتخاب کنید', 'بدون حرف‌زدن آن را نشان دهید', 'پس از حدس نقش‌ها را عوض کنید'], 'حرکت‌ها بدون دویدن، پرتاب یا تقلید کار خطرناک باشند', '7-9y', 84, 120, 1, 'harvard', ['duration_min_minutes' => 8, 'duration_max_minutes' => 20, 'space_required' => 'room', 'child_energy' => 'medium', 'interaction_type' => 'pretend', 'locations' => ['home-inside', 'travel'], 'moods' => ['restless', 'excited'], 'tags' => ['creative', 'movement'], 'player_requirement' => 'two-players', 'safety_flags' => ['high_impact']]),
    $make('paper-tower-challenge', 'چالش برج کاغذی', 'با چند برگ کاغذ و بدون چسب، یک سازه ایستاده ساخته می‌شود', ['کاغذها را روی سطح صاف بگذارید', 'با تا کردن قطعه بسازید', 'نوبتی قطعه اضافه کنید'], 'کاغذ را نزدیک صورت پرتاب نکنید و تکه‌ها را جمع کنید', '7-9y', 84, 120, 2, 'harvard', ['duration_min_minutes' => 12, 'duration_max_minutes' => 25, 'prep_time_minutes' => 2, 'mess_level' => 'light', 'caregiver_involvement' => 'light', 'materials' => [['slug' => 'paper', 'requirement' => 'required', 'quantity_note' => '۳ تا ۵ برگ کاغذ باطله تمیز']], 'tags' => ['creative', 'cooperative'], 'player_requirement' => 'two-players', 'safety_flags' => ['ingestion']]),
    $make('chain-story', 'داستان زنجیره‌ای', 'هر نفر فقط یک جمله به داستان مشترک اضافه می‌کند', ['نفر اول شخصیت و مکان را معرفی کند', 'نفر بعد یک جمله ادامه دهد', 'پس از سه دور داستان را تمام کنید'], 'از موضوع ترسناک یا ناراحت‌کننده دوری کنید', '7-9y', 84, 120, 3, 'harvard', ['duration_min_minutes' => 8, 'duration_max_minutes' => 20, 'space_required' => 'lap', 'interaction_type' => 'conversation', 'locations' => ['home-inside', 'travel'], 'moods' => ['calm', 'sad'], 'tags' => ['language', 'creative'], 'player_requirement' => 'two-players']),
    $make('soft-ball-target', 'هدف‌گیری با توپ نرم', 'بازیکن‌ها توپ نرم را به محدوده‌ای روی زمین هدایت می‌کنند و امتیاز گروهی می‌سازند', ['یک محدوده امن تعیین کنید', 'از فاصله کوتاه توپ را قل دهید', 'امتیازها را برای رکورد مشترک جمع کنید'], 'توپ فقط روی زمین قل داده شود و اطراف خالی باشد', '7-9y', 84, 120, 4, 'unicef-play', ['duration_min_minutes' => 10, 'duration_max_minutes' => 20, 'prep_time_minutes' => 2, 'space_required' => 'large', 'noise_level' => 'moderate', 'child_energy' => 'high', 'caregiver_energy' => 'medium', 'locations' => ['home-outside', 'park'], 'moods' => ['restless', 'excited'], 'tags' => ['movement', 'cooperative'], 'player_requirement' => 'two-players', 'materials' => [['slug' => 'ball', 'requirement' => 'required', 'quantity_note' => 'یک توپ نرم و سبک']], 'safety_flags' => ['high_impact', 'traffic_outdoor']]),

    $make('twenty-questions', 'بیست سؤال خانوادگی', 'یک نفر چیزی را در ذهن نگه می‌دارد و دیگران با سؤال‌های بله یا خیر آن را پیدا می‌کنند', ['یک موضوع آشنا انتخاب کنید', 'فقط سؤال بله یا خیر بپرسید', 'پس از حدس انتخاب‌کننده را عوض کنید'], 'موضوع‌ها را محترمانه و غیرشخصی نگه دارید', '10-12y', 120, 156, 0, 'harvard-7-12', ['duration_min_minutes' => 10, 'duration_max_minutes' => 25, 'space_required' => 'lap', 'interaction_type' => 'conversation', 'locations' => ['home-inside', 'travel'], 'moods' => ['calm', 'sad'], 'tags' => ['language', 'cooperative'], 'player_requirement' => 'two-players']),
    $make('silent-mission', 'مأموریت بی‌صدا', 'گروه باید یک کار ساده را بدون حرف‌زدن و فقط با اشاره هماهنگ کند', ['یک مأموریت امن انتخاب کنید', 'تا پایان مأموریت حرف نزنید', 'درباره اشاره‌های مؤثر گفت‌وگو کنید'], 'مأموریت شامل دویدن، بالارفتن یا وسیله سنگین نباشد', '10-12y', 120, 156, 1, 'harvard-7-12', ['duration_min_minutes' => 10, 'duration_max_minutes' => 20, 'prep_time_minutes' => 2, 'space_required' => 'room', 'mess_level' => 'light', 'child_energy' => 'medium', 'caregiver_involvement' => 'light', 'player_requirement' => 'two-players', 'materials' => [['slug' => 'cups', 'requirement' => 'optional', 'quantity_note' => 'چند لیوان سبک برای مأموریت نمونه']], 'safety_flags' => ['fall_height']]),
    $make('design-a-paper-game', 'بازی کاغذی خودمان', 'کودک و همراه با چند قانون ساده یک بازی رومیزی کوچک طراحی می‌کنند', ['هدف بازی را در یک جمله بنویسید', 'سه قانون کوتاه تعیین کنید', 'یک دور آزمایشی اجرا و یک قانون را بهتر کنید'], 'از مهره ریز، ابزار برنده و قانون تنبیهی استفاده نکنید', '10-12y', 120, 156, 2, 'harvard-7-12', ['duration_min_minutes' => 20, 'duration_max_minutes' => 40, 'prep_time_minutes' => 3, 'mess_level' => 'light', 'interaction_type' => 'cooperative', 'setup_complexity' => 'moderate', 'materials' => [['slug' => 'paper', 'requirement' => 'required', 'quantity_note' => 'چند برگ کاغذ']], 'tags' => ['creative', 'cooperative'], 'player_requirement' => 'two-players', 'safety_flags' => ['small_parts']]),
    $make('funny-debate', 'مناظره‌ی خنده‌دار', 'دو طرف از انتخاب‌های بی‌خطر و خیالی دفاع می‌کنند و سپس جای‌شان را عوض می‌کنند', ['یک موضوع سبک انتخاب کنید', 'هر نفر یک دقیقه دلیل بگوید', 'نقش‌ها را عوض کنید'], 'موضوع درباره ظاهر، هویت یا نقطه‌ضعف افراد نباشد', '10-12y', 120, 156, 3, 'harvard-7-12', ['duration_min_minutes' => 10, 'duration_max_minutes' => 20, 'space_required' => 'lap', 'noise_level' => 'moderate', 'child_energy' => 'medium', 'interaction_type' => 'conversation', 'locations' => ['home-inside', 'travel'], 'moods' => ['calm', 'sad'], 'tags' => ['language', 'creative'], 'player_requirement' => 'two-players']),
    $make('paper-bridge', 'پل کاغذی', 'گروه با تا کردن کاغذ پلی می‌سازد که یک لیوان خالی را نگه دارد', ['دو تکیه‌گاه سبک آماده کنید', 'کاغذ را تا کنید و میان آن‌ها بگذارید', 'با یک لیوان خالی پل را آزمایش کنید'], 'فقط لیوان خالی و سبک استفاده شود و جسم شیشه‌ای وارد بازی نشود', '10-12y', 120, 156, 4, 'harvard-7-12', ['duration_min_minutes' => 15, 'duration_max_minutes' => 35, 'prep_time_minutes' => 3, 'mess_level' => 'light', 'caregiver_involvement' => 'light', 'setup_complexity' => 'moderate', 'materials' => [['slug' => 'paper', 'requirement' => 'required', 'quantity_note' => '۲ تا ۴ برگ کاغذ'], ['slug' => 'cups', 'requirement' => 'optional', 'quantity_note' => 'یک لیوان خالی و سبک']], 'tags' => ['creative', 'cooperative'], 'player_requirement' => 'two-players', 'safety_flags' => ['sharp_object']]),
];
