@extends('errors.layout')
@section('title', 'زمان صفحه تمام شد')
@section('code', '۴۱۹')
@section('heading', 'زمان این صفحه تمام شد')
@section('message', 'برای امنیت شما، صفحه را تازه کنید و دوباره ادامه دهید. پاسخ‌های ثبت‌شده تا این مرحله در همان نشست می‌مانند.')
@section('retry', 'تازه‌کردن صفحه')
