<x-layouts.app title="دسته‌بندی‌های مجله" description="مدیریت موضوع‌های مجله تیله">
    <div class="admin-shell teelle-container">
        <header class="admin-heading"><div><p class="admin-kicker">مجله تیله</p><h1>دسته‌بندی‌های موضوعی</h1></div><a href="{{ route('admin.content.articles.index') }}">بازگشت</a></header>
        @if(session('status'))<p class="admin-notice" role="status">{{ session('status') }}</p>@endif
        @if($errors->any())<div class="admin-error" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <section class="admin-panel"><h2>دسته تازه</h2><form class="admin-form admin-form-grid" method="post" action="{{ route('admin.content.article-categories.store') }}">@csrf
            <label>عنوان<input class="teelle-input" name="title" required></label><label>نام کوتاه انگلیسی<input class="teelle-input" dir="ltr" name="slug" required></label><label>زیرمجموعه<select class="teelle-input" name="parent_id"><option value="">دسته اصلی</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->title }}</option>@endforeach</select></label><label>ترتیب<input class="teelle-input" type="number" name="sort_order" value="0" min="0" max="1000"></label><label class="admin-field-wide">توضیح<textarea class="teelle-input" name="description" rows="3"></textarea></label><input type="hidden" name="is_active" value="1"><x-ui.button type="submit">ساخت دسته</x-ui.button>
        </form></section>
        @foreach($categories as $category)<section class="admin-panel"><form class="admin-form admin-form-grid" method="post" action="{{ route('admin.content.article-categories.update', $category) }}">@csrf @method('PUT')
            <label>عنوان<input class="teelle-input" name="title" value="{{ $category->title }}" required></label><label>نام کوتاه انگلیسی<input class="teelle-input" dir="ltr" name="slug" value="{{ $category->slug }}" required></label><label>زیرمجموعه<select class="teelle-input" name="parent_id"><option value="">دسته اصلی</option>@foreach($categories->where('id', '!=', $category->id) as $parent)<option value="{{ $parent->id }}" @selected($category->parent_id === $parent->id)>{{ $parent->title }}</option>@endforeach</select></label><label>ترتیب<input class="teelle-input" type="number" name="sort_order" value="{{ $category->sort_order }}" min="0" max="1000"></label><label class="admin-field-wide">توضیح<textarea class="teelle-input" name="description" rows="3">{{ $category->description }}</textarea></label><input type="hidden" name="is_active" value="0"><label class="teelle-check"><input type="checkbox" name="is_active" value="1" @checked($category->is_active)><span>فعال باشد</span></label><x-ui.button type="submit" variant="secondary">ذخیره</x-ui.button>
        </form></section>@endforeach
    </div>
</x-layouts.app>
